# 1

In [2]:
import numpy as np
array=np.random.random([3,3,3])
print(array)

[[[0.74239615 0.69504204 0.77431943]
  [0.88342447 0.80116021 0.27267322]
  [0.81972262 0.49310701 0.18311391]]

 [[0.76130074 0.90085253 0.06441285]
  [0.17251412 0.12659784 0.78382504]
  [0.3231597  0.35433046 0.39482209]]

 [[0.02607805 0.98235774 0.64020343]
  [0.3240716  0.29620713 0.74436038]
  [0.0977837  0.42922035 0.05166287]]]


# 2

In [4]:
import numpy as np
array=np.diag([1,2,3,4])
print(array)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 3

In [5]:
import numpy as np
x = np.ones((8,8))
print("Checkerboard pattern:")


Checkerboard pattern:


In [6]:
import numpy as np

print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [12]:
import numpy as np
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1


print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4

In [14]:
import numpy as np
array=np.random.random([5,5])
print(array)
xmax=array.max()
xmin=array.min()
z=(array-xmin)/(xmax-xmin)
print(z)

[[0.66556075 0.59044676 0.75367142 0.80306212 0.8930378 ]
 [0.90412685 0.64486663 0.21429107 0.18011649 0.63899506]
 [0.63232676 0.29005047 0.79433419 0.01856985 0.54247906]
 [0.2262073  0.41133565 0.66692444 0.38426146 0.1560335 ]
 [0.47721285 0.8210749  0.09593357 0.33023612 0.05139592]]
[[0.73060334 0.64578216 0.8301008  0.88587439 0.98747788]
 [1.         0.70723486 0.22101481 0.18242376 0.70060448]
 [0.69307443 0.30656481 0.87601852 0.         0.59161546]
 [0.23447101 0.44352401 0.73214326 0.41295095 0.15522846]
 [0.51791471 0.90621501 0.08736164 0.35194377 0.03706827]]


# 5

In [3]:
import numpy as np
array1=np.array([10,20,30])
array2=np.array([10,40,50])
print(np.intersect1d(array1,array2))


[10]


In [2]:
array1 = np.array([10,20,30])
print(array1)
array2=np.array([10,40,50])
print(array2)
print(np.intersect1d(array1, array2))

[10 20 30]
[10 40 50]
[10]


# 6

In [5]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7

In [6]:
array1 = np.array([10,20,30])
print(array1)
array2=np.array([10,40,50])
print(array2)
print(np.allclose(array1, array2))

[10 20 30]
[10 40 50]
False


# 8

In [7]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.87461769 0.46217814 0.22868581 0.47006756 0.13395648 0.92236718
 0.63201875 0.00715676 0.3026327  0.42231008]
Maximum value replaced by 0:
[0.87461769 0.46217814 0.22868581 0.47006756 0.13395648 0.
 0.63201875 0.00715676 0.3026327  0.42231008]


# 9

In [8]:
array1 = np.array([10,20,30,40,50])
print(array1)

[10 20 30 40 50]


# 10

In [10]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(10, 20)
print(X)
print(" array after subtract each raw with mean")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.96611214 0.78593214 0.33361928 0.08358137 0.48454359 0.8726908
  0.41460863 0.23787284 0.87444827 0.78141537 0.3610473  0.12964021
  0.0413256  0.90917064 0.63099182 0.68186066 0.31791438 0.13805999
  0.05101514 0.84792944]
 [0.38931339 0.12255261 0.89061379 0.98467863 0.58219513 0.75812681
  0.79071411 0.74024229 0.33878551 0.6458375  0.3831212  0.58788345
  0.90597662 0.92756216 0.953145   0.69995408 0.58760375 0.3792931
  0.31280559 0.0312945 ]
 [0.48553969 0.47802236 0.20552765 0.78893213 0.90037909 0.86726319
  0.24296085 0.31487258 0.63410278 0.36705256 0.84504051 0.5738113
  0.00408899 0.06235142 0.33866947 0.28538701 0.15765404 0.59613636
  0.61262981 0.48896697]
 [0.35579407 0.06907039 0.32611213 0.39583487 0.7146496  0.45741818
  0.22413952 0.40658822 0.73863816 0.70953702 0.56727619 0.56553467
  0.07407678 0.00875853 0.14273105 0.75697516 0.67199616 0.69145466
  0.16332414 0.10476686]
 [0.11729214 0.96059426 0.72887961 0.61427233 0.04852214 0.18022655
 

# 14

In [12]:
array1 = np.array([10,20,30,40,50])
print(array1.max())

50


# 13

In [18]:
array1 = np.array([10,20,30])
print(array1)

[10 20 30]


In [21]:
import numpy as np
x = np.random.randint(0, 10, 40)
print(x)

[9 0 5 9 1 2 9 4 9 1 7 2 8 9 5 2 7 3 1 7 9 7 7 7 9 6 4 1 9 9 2 0 1 1 7 3 2
 1 7 2]


In [22]:
print(np.bincount(x).argmax())

9


# 11

In [26]:
array1 = np.ones((3,3))
print(array1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
array2 = ([1,2,3])
print(array2)

[1, 2, 3]


In [29]:
add_raw=array1+array2
print(add_raw)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


# 14

In [30]:
import numpy as np
x = np.arange(20)


np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

[19]


# 15

In [31]:
import numpy as np
arra1 = np.array([("A", 66.5, 90),
                 ("B", 88, 99),
             ("C", 85.5, 91)])

print(arra1)

result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

[['A' '66.5' '90']
 ['B' '88' '99']
 ['C' '85.5' '91']]
[(b'A', 66.5, 90) (b'B', 88. , 99) (b'C', 85.5, 91)]
